export const CHARACTERS = {
  ALI: "ALI",
  ALICIA: "ALICIA",
  BAKAR: "BAKAR",
  COMOT: "COMOT",
  JET: "JET",
  ZASS: "ZASS",
};

export const OBSTACLES = {
  WALLS: "WALLS",
  ROCKETS: "ROCKETS",
  LASERDROIDS: "LASERDROIDS",
  WALLSROCKETS: "WALLSROCKETS",
};

export const DROID_NAMES = {
  SMALLDROID: "SMALLDROID",
  SMALLDROIDROPE: "SMALLDROIDROPE",
  BIGDROID: "BIGDROID",
  BIGDROIDROPE: "BIGDROIDROPE",
};

export const ISRESTART = "isRestart";
