const DROID_NAMES = {
  SMALLDROID: "SMALLDROID",
  SMALLDROIDROPE: "SMALLDROIDROPE",
  BIGDROID: "BIGDROID",
  BIGDROIDROPE: "BIGDROIDROPE",
};

const droidGroup1 = [DROID_NAMES.SMALLDROID, DROID_NAMES.SMALLDROID];

const droidGroup2 = [DROID_NAMES.SMALLDROID, DROID_NAMES.BIGDROID];

const droidGroup3 = [
  DROID_NAMES.SMALLDROID,
  DROID_NAMES.SMALLDROID,
  DROID_NAMES.BIGDROID,
];

const droidGroup4 = [
  DROID_NAMES.SMALLDROID,
  DROID_NAMES.SMALLDROID,
  DROID_NAMES.BIGDROIDROPE,
];

const droidGroup5 = [
  DROID_NAMES.SMALLDROID,
  DROID_NAMES.SMALLDROID,
  DROID_NAMES.BIGDROIDROPE,
  DROID_NAMES.SMALLDROIDROPE,
];

const droidGroupsArr = [
  droidGroup1,
  droidGroup2,
  droidGroup3,
  droidGroup4,
  droidGroup5,
];

export default droidGroupsArr;
